"""initial_app_schema

Revision ID: e53ebac3a6e5
Revises: 
Create Date: 2026-08-30 22:13:44.812758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53ebac3a6e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assistant_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_hash', sa.String(length=64), nullable=False),
    sa.Column('request_class', sa.String(length=64), nullable=False),
    sa.Column('tools_called', sa.JSON(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('policy_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_event_player_id'), 'availability_event', ['player_id'], unique=False)
    op.create_table('decision_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('projection_run_id', sa.String(length=36), nullable=False),
    sa.Column('roster_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_snapshot_league_id'), 'decision_snapshot', ['league_id'], unique=False)
    op.create_table('depth_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('injury_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=512), nullable=False),
    sa.Column('claim_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injury_evidence_player_id'), 'injury_evidence', ['player_id'], unique=False)
    op.create_table('job_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_job_run_correlation_id'), 'job_run', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_job_run_job_name'), 'job_run', ['job_name'], unique=False)
    op.create_table('league',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('league_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('previous_league_id', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', name='uq_league_season')
    )
    op.create_index(op.f('ix_league_league_id'), 'league', ['league_id'], unique=False)
    op.create_table('league_draft_rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('rule', sa.String(length=32), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_draft_rule_league_id'), 'league_draft_rule', ['league_id'], unique=False)
    op.create_table('league_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'roster_id', name='uq_league_roster')
    )
    op.create_index(op.f('ix_league_member_league_id'), 'league_member', ['league_id'], unique=False)
    op.create_table('league_rule_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('normalized_json', sa.JSON(), nullable=False),
    sa.Column('contract_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_rule_snapshot_league_id'), 'league_rule_snapshot', ['league_id'], unique=False)
    op.create_table('league_transaction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('txn_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_league_transaction_league_id'), 'league_transaction', ['league_id'], unique=False)
    op.create_table('magic_link_token',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_magic_link_token_email'), 'magic_link_token', ['email'], unique=False)
    op.create_table('manager_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('probabilities_json', sa.JSON(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('overridden_label', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_state_league_id'), 'manager_state', ['league_id'], unique=False)
    op.create_table('manager_tendency',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_tendency_league_id'), 'manager_tendency', ['league_id'], unique=False)
    op.create_table('matchup_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchup_snapshot_league_id'), 'matchup_snapshot', ['league_id'], unique=False)
    op.create_table('player_identity',
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('sleeper_id', sa.String(length=64), nullable=True),
    sa.Column('gsis_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_player_identity_sleeper_id'), 'player_identity', ['sleeper_id'], unique=False)
    op.create_table('player_status_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('injury_status', sa.String(length=32), nullable=True),
    sa.Column('practice', sa.String(length=32), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_status_snapshot_player_id'), 'player_status_snapshot', ['player_id'], unique=False)
    op.create_table('projection_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('manifest_uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projection_run_mode'), 'projection_run', ['mode'], unique=False)
    op.create_table('promotion_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('candidate_run_id', sa.String(length=36), nullable=False),
    sa.Column('previous_run_id', sa.String(length=36), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('validation_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.Column('starters', sa.JSON(), nullable=False),
    sa.Column('reserve', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_snapshot_league_id'), 'roster_snapshot', ['league_id'], unique=False)
    op.create_table('sleeper_account',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('source_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('request_params_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=False),
    sa.Column('health_verdict', sa.String(length=32), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_proposal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_roster_id', sa.Integer(), nullable=False),
    sa.Column('sides_json', sa.JSON(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('countered_by_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_proposal_league_id'), 'trade_proposal', ['league_id'], unique=False)
    op.create_table('traded_pick',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('original_roster_id', sa.Integer(), nullable=False),
    sa.Column('owner_roster_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traded_pick_league_id'), 'traded_pick', ['league_id'], unique=False)
    op.create_table('active_projection_pointer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_run_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['projection_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mode', 'season', 'week', name='uq_active_pointer')
    )
    op.create_table('player_projection',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('opponent', sa.String(length=8), nullable=True),
    sa.Column('availability_probability', sa.Float(), nullable=True),
    sa.Column('mean_json', sa.JSON(), nullable=False),
    sa.Column('quantiles_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['projection_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_projection_player_id'), 'player_projection', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_projection_run_id'), 'player_projection', ['run_id'], unique=False)
    op.create_table('session_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_hash', sa.String(length=128), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_hash')
    )
    op.create_table('simulation_partition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('partition_key', sa.String(length=128), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('draw_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['projection_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_partition_run_id'), 'simulation_partition', ['run_id'], unique=False)
    op.create_table('trade_evaluation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('projection_run_id', sa.String(length=36), nullable=False),
    sa.Column('objective_json', sa.JSON(), nullable=False),
    sa.Column('fairness_json', sa.JSON(), nullable=False),
    sa.Column('acceptance_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_evaluation')
    op.drop_index(op.f('ix_simulation_partition_run_id'), table_name='simulation_partition')
    op.drop_table('simulation_partition')
    op.drop_table('session_record')
    op.drop_index(op.f('ix_player_projection_run_id'), table_name='player_projection')
    op.drop_index(op.f('ix_player_projection_player_id'), table_name='player_projection')
    op.drop_table('player_projection')
    op.drop_table('active_projection_pointer')
    op.drop_index(op.f('ix_traded_pick_league_id'), table_name='traded_pick')
    op.drop_table('traded_pick')
    op.drop_index(op.f('ix_trade_proposal_league_id'), table_name='trade_proposal')
    op.drop_table('trade_proposal')
    op.drop_table('source_snapshot')
    op.drop_table('sleeper_account')
    op.drop_index(op.f('ix_roster_snapshot_league_id'), table_name='roster_snapshot')
    op.drop_table('roster_snapshot')
    op.drop_table('promotion_event')
    op.drop_index(op.f('ix_projection_run_mode'), table_name='projection_run')
    op.drop_table('projection_run')
    op.drop_index(op.f('ix_player_status_snapshot_player_id'), table_name='player_status_snapshot')
    op.drop_table('player_status_snapshot')
    op.drop_index(op.f('ix_player_identity_sleeper_id'), table_name='player_identity')
    op.drop_table('player_identity')
    op.drop_index(op.f('ix_matchup_snapshot_league_id'), table_name='matchup_snapshot')
    op.drop_table('matchup_snapshot')
    op.drop_index(op.f('ix_manager_tendency_league_id'), table_name='manager_tendency')
    op.drop_table('manager_tendency')
    op.drop_index(op.f('ix_manager_state_league_id'), table_name='manager_state')
    op.drop_table('manager_state')
    op.drop_index(op.f('ix_magic_link_token_email'), table_name='magic_link_token')
    op.drop_table('magic_link_token')
    op.drop_index(op.f('ix_league_transaction_league_id'), table_name='league_transaction')
    op.drop_table('league_transaction')
    op.drop_index(op.f('ix_league_rule_snapshot_league_id'), table_name='league_rule_snapshot')
    op.drop_table('league_rule_snapshot')
    op.drop_index(op.f('ix_league_member_league_id'), table_name='league_member')
    op.drop_table('league_member')
    op.drop_index(op.f('ix_league_draft_rule_league_id'), table_name='league_draft_rule')
    op.drop_table('league_draft_rule')
    op.drop_index(op.f('ix_league_league_id'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_job_run_job_name'), table_name='job_run')
    op.drop_index(op.f('ix_job_run_correlation_id'), table_name='job_run')
    op.drop_table('job_run')
    op.drop_index(op.f('ix_injury_evidence_player_id'), table_name='injury_evidence')
    op.drop_table('injury_evidence')
    op.drop_table('depth_snapshot')
    op.drop_index(op.f('ix_decision_snapshot_league_id'), table_name='decision_snapshot')
    op.drop_table('decision_snapshot')
    op.drop_index(op.f('ix_availability_event_player_id'), table_name='availability_event')
    op.drop_table('availability_event')
    op.drop_table('assistant_audit')
    op.drop_table('app_user')
    # ### end Alembic commands ###
